export { databaseManager, DatabaseManager, DatabaseConnection, EnterpriseDexieDatabase, DB_NAME } from './DatabaseManager';
export { DatabaseManagerFactory } from './DatabaseManagerFactory';
export { repositories, getRepository, getRepositories } from './repositories';
export { dexieBridge } from './bridge';
export { settingsBackplane } from './settings-backplane';
export { dexieQueueCoordinator } from './queue-coordinator';
export { syncEngine, SyncEngine } from './sync/SyncEngine';
export { syncQueue, SyncQueue } from './sync/SyncQueue';
export { backgroundSync, BackgroundSync } from './sync/BackgroundSync';
export { conflictResolver, ConflictResolver } from './sync/ConflictResolver';
export { defaultRetryPolicy, RetryPolicy } from './sync/RetryPolicy';
export { analyticsCache, AnalyticsCache } from './analytics/AnalyticsCache';
export { aggregationService, AggregationService } from './analytics/Aggregations';
export { dashboardSnapshotService, DashboardSnapshotService } from './analytics/DashboardSnapshot';
export { startupOrchestrator, StartupOrchestrator } from './startup/StartupOrchestrator';
export { phaseManager, PhaseManager } from './startup/PhaseManager';
export { PriorityResolver } from './startup/PriorityResolver';
export { auditLogger, AuditLogger } from './security/AuditLogger';
export { workspaceIsolation, WorkspaceIsolation } from './security/WorkspaceIsolation';
export { backupService, BackupService } from './utils/backup';
export { dataExportService, DataExportService } from './utils/export';
export { checkIntegrity, findOrphans } from './utils/integrity';
export { validateSchema } from './utils/validation';
export { useLiveQuery, useLiveObject, useRepositoryQuery, useRepositoryObject, usePaginatedQuery } from './reactive/hooks';
export { createLiveQuery, observeTable, observeTableById } from './reactive/liveQuery';
export { QueryCache, queryCache } from './reactive/cache';
export { SubscriptionManager, subscriptionManager } from './reactive/subscriptions';
export { BaseRepository } from './repositories/BaseRepository';
export * from './repositories';
export * from './types';
export * from './normalizers';
export { CORE_TABLES, FINANCE_TABLES, INVENTORY_TABLES, PRODUCTION_TABLES, EXAMINATION_TABLES, ANALYTICS_TABLES, SYNC_TABLES, ALL_TABLES, TABLE_DEFINITIONS, DOMAIN_TABLE_MAP } from './schema-types';
